# Generated by Django 4.2.3 on 2023-07-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_remove_question_incorrect_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='incorrect_answers',
            field=models.ManyToManyField(to='Quiz.incorrectanswer'),
        ),
    ]
