# Generated by Django 4.2.3 on 2023-07-09 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_question_incorrect_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='incorrect_answers',
        ),
    ]
