# Generated by Django 4.2.3 on 2023-07-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_remove_question_incorrect_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
