# Generated by Django 4.2.3 on 2023-07-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetincorrectanswer',
            name='incorrect_answer',
        ),
        migrations.RemoveField(
            model_name='presetincorrectanswer',
            name='preset_question',
        ),
        migrations.RemoveField(
            model_name='presetquestion',
            name='modified_incorrect_answers',
        ),
        migrations.RemoveField(
            model_name='presetquestion',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='presetquestion',
            name='question',
        ),
        migrations.RemoveField(
            model_name='presetquestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quizpreset',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quizpreset',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='PresetIncorrectAnswer',
        ),
        migrations.DeleteModel(
            name='PresetQuestion',
        ),
        migrations.DeleteModel(
            name='QuizPreset',
        ),
    ]
