# Generated by Django 4.2.3 on 2023-07-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_remove_course_student_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
