# Generated by Django 4.2.3 on 2023-07-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0012_alter_quizresult_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizresult',
            name='grade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
